# Generated by Django 2.1 on 2018-09-17 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180909_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='job',
            name='fullsummary',
            field=models.TextField(default='Un récit'),
        ),
        migrations.AddField(
            model_name='job',
            name='titre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(default='Une description courte'),
        ),
    ]
