# Generated by Django 2.1 on 2018-09-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
